### ISSUE TITLE
请求的部门id不在授权范围内","errcode":50004  企业内部开发，access-token获取成功

### ISSUE THREAD

**Issue by sdaduanbilei** [open-dingtalk/openapi-demo-java#1]
文档链接
[https:// open-doc.dingtalk.com/docs/doc.htm?spm=a219a.7629140.0.0.WIrWgy&treeId=172&articleId=104979&docType=1#s0]()

- 获取部门列表
- Https请求方式: GET
- https:// oapi.dingtalk.com/department/list?access_token=ACCESS_TOKEN

返回错误信息
```json
{"errmsg":"请求的部门id不在授权范围内","errcode":50004}
```

**Comment by sdaduanbilei** [comment]
去开发者管理端重新生成```corpsecret```
![https://ws2.sinaimg.cn/large/006tNc79gy1fj8snggm9qj30tc0lc404.jpg]()

**Comment by opendingtalk** [comment]
"请求的部门id不在授权范围内" 这种错误可以通过接口 https://oapi.dingtalk.com/auth/scopes?access_token=ACCESS_TOKEN 来查看accessToken拥有权限的通讯录列表
